HOSTS:
  ubuntu-server-1404-x64:
    roles:
      - default
      - ubuntu
    platform: ubuntu-14.04-amd64
    box: puppetlabs/ubuntu-14.04-64-nocm
    hypervisor: vagrant
CONFIG:
  type: foss
  masterless: true
  log_level: debug
