source ENV['GEM_SOURCE'] || 'https://rubygems.org'

puppetversion = ENV.key?('PUPPET_VERSION') ? "#{ENV['PUPPET_VERSION']}" : ['>= 3.3']
gem 'metadata-json-lint'
gem 'puppet', puppetversion
gem 'puppetlabs_spec_helper', '>= 1.0.0'
gem 'puppet-lint', '>= 1.0.0'
gem 'facter', '>= 1.7.0'
gem 'rspec-puppet'

# rspec must be v2 for ruby 1.8.7
if RUBY_VERSION >= '1.8.7' and RUBY_VERSION < '1.9'
  gem 'rspec', '~> 2.0'
end

group :test do
  gem "rake"
  gem "puppet", ENV['PUPPET_VERSION'] || '= 4.2.1'
  gem "rspec-puppet"
  gem "rspec"
  gem "puppetlabs_spec_helper"
  gem 'puppet-catalog-test','~> 0.3.2'
  gem 'hiera-eyaml'
end

group :development do
  gem "beaker","~> 2.20.0"
  gem "beaker-rspec"
  gem 'rspec_junit_formatter'
  gem "puppet-blacksmith"
  gem "guard","~> 2.8.0"
  gem "guard-rake", '~> 1.0.0'
  gem 'listen', '~> 2.7.0'
  gem "ruby_gntp"
  gem "colorize"
end
