source ENV['GEM_SOURCE'] || "https://rubygems.org"

group :development, :test do
  gem 'rake'
  gem 'puppetlabs_spec_helper', :require => false
  gem 'rspec-core', '~> 3.4.4'
  gem 'rspec-puppet', '~> 2.4.0'
  gem 'puppet-lint',  '~> 1.1'
  gem 'metadata-json-lint'
end

group :system_tests do
  gem 'beaker',                :require => false
  gem 'beaker-rspec',          :require => false
  gem 'serverspec',            :require => false
end

if puppetversion = ENV['PUPPET_GEM_VERSION']
  gem 'puppet', puppetversion, :require => false
else
  gem 'puppet', :require => false
end

eval_gemfile('Gemfile.local') if File.file?('Gemfile.local')
