# This file is generated by ModuleSync, do not edit.

source ENV['GEM_SOURCE'] || 'https://rubygems.org'

group :development, :test do
  gem 'json', '< 2.0.0',                :require => false
  gem 'json_pure', '< 2.0.0',           :require => false
  gem 'tins', '< 1.7.0',                :require => false
  gem 'rake',                           :require => false
  gem 'rspec',                          :require => false
  gem 'rspec-puppet', '>= 2.2.0',       :require => false
  gem 'puppetlabs_spec_helper',         :require => false
  gem 'metadata-json-lint',             :require => false
  gem 'librarian-puppet',               :require => false
  gem 'rspec-puppet-facts', '>= 1.1.1', :require => false
  gem 'coveralls',                      :require => false
end

if RUBY_VERSION < '1.9'
  gem 'oniguruma', :require => false
end

if facterversion = ENV['FACTER_GEM_VERSION']
  gem 'facter', facterversion, :require => false
else
  gem 'facter', :require => false
end

if puppetversion = ENV['PUPPET_GEM_VERSION']
  gem 'puppet', puppetversion, :require => false
else
  gem 'puppet', :require => false
end
