<<<<<<< HEAD
#This file is generated by ModuleSync, do not edit.
=======
RSpec.configure do |c|
  c.mock_with :rspec
end

# This file is generated by ModuleSync, do not edit.
>>>>>>> f661b3a03526f113b1823084ffd4808cf261cf70
require 'puppetlabs_spec_helper/module_spec_helper'

if Puppet::Util::Package.versioncmp(Puppet.version, '4.5.0') >= 0
  RSpec.configure do |c|
    c.before :each do
      Puppet.settings[:strict] = :error
    end
  end
end

<<<<<<< HEAD
=======
def ensure_module_defined(module_name)
  module_name.split('::').reduce(Object) do |last_module, next_module|

    last_module.const_set(next_module, Module.new) unless last_module.const_defined?(next_module, false)
    last_module.const_get(next_module, false)
  end
end

>>>>>>> f661b3a03526f113b1823084ffd4808cf261cf70
# put local configuration and setup into spec_helper_local
begin
  require 'spec_helper_local'
rescue LoadError
end
