# syntax=docker/dockerfile:1.0.0-experimental
FROM ruby:2.5.1-alpine
RUN apk add --no-cache git openssh ruby-dev make libxml2 libxslt-dev g++
COPY Gemfile /app/
COPY Rakefile /app/
WORKDIR /app
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh,id=sshkey bundle install --path=/app/.bundle
ENV BUNDLE_GEMFILE=/app/Gemfile
VOLUME /code
WORKDIR /code
ENTRYPOINT ["bundle","exec","rake"]
CMD ["parallel_spec"]

### This is a Dockerfile to run spec test in a container using --ssh option to forward ssh key during image build
### The secret mount option requires Docker Edge 18.09 version
### Make sure to include the comment in the first line. The new feature requires a release from the experimental channel as of 11/15/2018
### This is an opt-in feature for now, which requires setting of following environment variable
### export DOCKER_BUILDKIT=1
### The image can be built and run using following commands
### docker build --ssh sshkey=$HOME/.ssh/id_rsa -f Dockerfile_ssh -t specdocker .
### docker run -v $HOME/.ssh:/root/.ssh -v `pwd`:/code specdocker
