require 'puppetlabs_spec_helper/rake_tasks'
require 'puppet_blacksmith/rake_tasks'

require 'puppet-lint'
Dir.glob('./rake_tasks/*.rake').each { |r| load r}

PuppetLint.configuration.ignore_paths = ["pkg/**/*.pp", "spec/fixtures/**/*.pp"]
PuppetLint.configuration.send('disable_class_parameter_defaults')
PuppetLint.configuration.send('disable_80chars')
PuppetLint.configuration.send('disable_quoted_booleans')
PuppetLint.configuration.send('disable_documentation')
PuppetLint.configuration.send('disable_class_inherits_from_params_class')
PuppetLint.configuration.send('disable_arrow_alignment')
PuppetLint.configuration.send('disable_2sp_soft_tabs')

desc 'run static analysis with rubocop'
task(:rubocop) do
  # We will always have Ruby 2.1.9 or above
  require 'rubocop'
  cli = RuboCop::CLI.new
  exit cli.run(%w(-D -f s))
end
